#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Marcel Petrick <mail@marcelpetrick.it>
#
# generate_coverage_imports.sh – make untested files visible to coverage.
#
# Usage:   tool/generate_coverage_imports.sh
#
# `flutter test --coverage` only reports libraries that some test loads, so a
# completely untested file would silently not count against the coverage gate.
# This script writes test/coverage_imports_test.dart (git-ignored), importing
# every hand-written library below lib/ so all of them appear in lcov.info.
# Generated localization code (lib/l10n/generated) is excluded.
#
# Exit codes: 0 success, 1 write error.
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
target="${root_dir}/test/coverage_imports_test.dart"

{
	echo '// GENERATED by tool/generate_coverage_imports.sh – do not edit.'
	echo '// ignore_for_file: unused_import, directives_ordering'
	(cd "${root_dir}" && find lib -name '*.dart' -not -path 'lib/l10n/generated/*' | sort) |
		sed 's|^lib/\(.*\)$|import '"'"'package:raumfreund/\1'"'"';|'
	echo
	echo "import 'package:flutter_test/flutter_test.dart';"
	echo
	echo "void main() => test('all libraries load', () {});"
} >"${target}"
